In [3]:
import pandas as pd
print("Hazırım.")

Hazırım.

In [4]:
import os
print(os.getcwd())
os.listdir()
# Amaç: Notebook'un hangi klasörde çalıştığını kontrol etmek.
# Böylece veri dosyalarını okurken doğru path kullanıldığından emin oluruz.
# Proje yapısının (data_raw, data_interim vb.) doğru konumda olduğunu doğrulamak için kullanılır.

/Users/aslitarakcilar/Desktop/Tez_Sephora/notebooks

['01_data_loading.ipynb']

In [5]:
import os
print(os.listdir(".."))

['.DS_Store', 'data_processed', 'requirements.txt', 'README.md', '.gitignore', 'data_raw', '.git', 'data_interim', 'outputs', 'notebooks', 'src']

In [6]:
import pandas as pd

products = pd.read_csv("../data_raw/product_info.csv")

print("Satır sayısı:", products.shape[0])
print("Sütun sayısı:", products.shape[1])

products.head()
# Amaç: Ham ürün veri setini yüklemek.
# Dataset 8494 ürün ve 27 özelliğe sahiptir.
# Bu veri daha sonra temizlenerek products_clean tablosuna dönüştürülecek.

Satır sayısı: 8494
Sütun sayısı: 27

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [7]:
import pandas as pd

products = pd.read_csv("../data_raw/product_info.csv")

print("Satır sayısı:", products.shape[0])
print("Sütun sayısı:", products.shape[1])

products.head()

Satır sayısı: 8494
Sütun sayısı: 27

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [8]:
products.info()
# Amaç: Ürün veri setinin genel yapısını incelemek.
# Hangi kolonların dolu/eksik olduğunu ve veri tiplerini görmek.
# Bu analiz, ileride hangi feature'ların kullanılacağına karar vermek için yapılmaktadır.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   object
 1   product_name        8494 non-null   object
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   object
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   object
 8   variation_type      7050 non-null   object
 9   variation_value     6896 non-null   object
 10  variation_desc      1250 non-null   object
 11  ingredients         7549 non-null   object
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   object
 21  primary_category    8494 non-null   object
 22  secondary_category  8486 non-null   object
 23  tertiary_category   7504 non-null   object
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), object(12)
memory usage: 1.7+ MB

In [9]:
null_percent = products.isna().mean().sort_values(ascending=False) * 100
null_percent
# Amaç: Ürün veri setindeki eksik değer oranlarını hesaplamak.
# Yüksek oranda eksik veri içeren kolonları belirlemek ve
# modelde kullanılmayacak feature'ları elemek için analiz yapılmaktadır.

sale_price_usd        96.821286
value_price_usd       94.690370
variation_desc        85.283730
child_max_price       67.577113
child_min_price       67.577113
highlights            25.983047
size                  19.201789
variation_value       18.813280
variation_type        17.000235
tertiary_category     11.655286
ingredients           11.125500
rating                 3.272899
reviews                3.272899
secondary_category     0.094184
sephora_exclusive      0.000000
brand_id               0.000000
child_count            0.000000
primary_category       0.000000
new                    0.000000
out_of_stock           0.000000
online_only            0.000000
limited_edition        0.000000
brand_name             0.000000
product_name           0.000000
price_usd              0.000000
loves_count            0.000000
product_id             0.000000
dtype: float64

In [10]:
products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [11]:
products[products["rating"].isna()].head()
# Amaç: Ürün veri setinde rating değeri eksik olan ürünleri incelemek.
# Rating'i olmayan ürünler profile-based skor hesaplamasında yer almayacaktır.
# Bu durum ileride cold-item problemini doğurabilir ve hybrid yaklaşımı gerektirebilir.

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
42,P471525,Arancia di Capri Candle,5847,Acqua di Parma,601,NaN,NaN,7 oz/ 200 g,Size + Concentration + Formulation,7 oz/ 200 g 1-wick Candle,...,1,0,0,NaN,Fragrance,Candles & Home Scents,Candles,0,NaN,NaN
60,P473154,Mini Baomint Moisturizing Curl Defining Gel,6321,adwoa beauty,0,NaN,NaN,3.3 oz/ 94 g,Size,3.3 oz/ 94 g,...,0,0,1,"['allure 2020 Best of Beauty Award Winner', 'C...",Hair,Mini Size,NaN,0,NaN,NaN
61,P473153,Mini Baomint Moisturizing Curl Defining Cream,6321,adwoa beauty,0,NaN,NaN,3.3 oz/ 94 g,Size,3.3 oz/ 94 g,...,1,0,1,"['Clean at Sephora', 'Good for: Volume', 'All ...",Hair,Mini Size,NaN,0,NaN,NaN
62,P473152,Mini Baomint Leave-In Conditioning Styler,6321,adwoa beauty,0,NaN,NaN,3.3 oz/ 98 mL,Size,3.3 oz/ 98 mL,...,1,0,1,"['Clean at Sephora', 'All Hair Types', 'Curl-E...",Hair,Mini Size,NaN,0,NaN,NaN
63,P473155,Mini Baomint Moisturizing Shampoo,6321,adwoa beauty,0,NaN,NaN,3.3 oz/ 98 mL,Size,3.3 oz/ 98 mL,...,1,0,1,"['Unisex/ Genderless Scent', 'Clean at Sephora...",Hair,Mini Size,NaN,0,NaN,NaN

In [12]:
cols_to_drop = [
    "brand_id",
    "variation_type",
    "variation_value",
    "variation_desc",
    "size",
    "value_price_usd",
    "sale_price_usd",
    "child_max_price",
    "child_min_price"
]

products_clean = products.drop(columns=cols_to_drop)

products_clean.shape
# Amaç: Yüksek oranda eksik veri içeren veya sistemde kullanılmayacak
# kolonları çıkararak ürün veri setini sadeleştirmek.
# Bu adım sonucunda products_clean, modelde kullanılacak ana ürün tablosu haline gelmiştir.

(8494, 18)

In [13]:
products_clean[["ingredients", "highlights"]].head(3)
# Amaç: ingredients ve highlights sütunlarının ham formatını incelemek.
# Bu alanlar liste gibi görünse de aslında string formatında tutuluyor.
# Bu nedenle product_text oluşturmadan önce düz metne dönüştürülmeleri gerekiyor.

,ingredients,highlights
0,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...","['Unisex/ Genderless Scent', 'Warm &Spicy Scen..."
1,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...","['Unisex/ Genderless Scent', 'Layerable Scent'..."
2,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...","['Unisex/ Genderless Scent', 'Layerable Scent'..."

In [14]:
type(products_clean["ingredients"].iloc[0])
# ingredients sütunundaki ilk değerin veri tipini kontrol ediyoruz.
# Eğer sonuç 'str' ise, bu sütun liste gibi görünse de aslında string olarak saklanmaktadır.
# Bu nedenle ileride listeyi parse ederek temiz metne dönüştürmemiz gerekecektir.

str

In [15]:
import ast

def safe_list_to_text(x):
    if pd.isna(x):
        return ""
    try:
        return " ".join(ast.literal_eval(x))
    except:
        return str(x)

products_clean["ingredients"] = products_clean["ingredients"].apply(safe_list_to_text)
products_clean["highlights"] = products_clean["highlights"].apply(safe_list_to_text)

products_clean[["ingredients", "highlights"]].head(3)

# Amaç:
# ingredients ve highlights sütunlarında liste gibi görünen string verileri
# düz metne dönüştürmek.
# Boş (NaN) değerler için boş string döndürülür.
# Böylece bu alanlar daha sonra product_text oluştururken temiz ve kullanılabilir hale gelir.

,ingredients,highlights
0,Capri Eau de Parfum: Alcohol Denat. (SD Alcoho...,Unisex/ Genderless Scent Warm &Spicy Scent Woo...
1,"Alcohol Denat. (SD Alcohol 39C), Parfum (Fragr...",Unisex/ Genderless Scent Layerable Scent Warm ...
2,"Alcohol Denat. (SD Alcohol 39C), Parfum (Fragr...",Unisex/ Genderless Scent Layerable Scent Woody...

In [16]:
text_cols = [
    "product_name",
    "brand_name",
    "primary_category",
    "secondary_category",
    "tertiary_category",
    "highlights",
    "ingredients"
]

products_clean["product_text"] = (
    products_clean[text_cols]
    .fillna("")
    .agg(" ".join, axis=1)
)

products_clean[["product_name", "product_text"]].head(3)

# Amaç:
# Ürünü temsil edecek tek bir metin alanı (product_text) oluşturmak.
# product_name, brand_name, kategori bilgileri, highlights ve ingredients
# sütunları birleştirilerek her ürün için açıklayıcı bir metin oluşturulur.
# Eksik değerler boş string ile doldurulur ve tüm alanlar tek metin halinde birleştirilir.

,product_name,product_text
0,Fragrance Discovery Set,Fragrance Discovery Set 19-69 Fragrance Value ...
1,La Habana Eau de Parfum,La Habana Eau de Parfum 19-69 Fragrance Women ...
2,Rainbow Bar Eau de Parfum,Rainbow Bar Eau de Parfum 19-69 Fragrance Wome...

In [17]:
import re

def minimal_clean(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

products_clean["product_text"] = products_clean["product_text"].apply(minimal_clean)

products_clean["product_text"].iloc[0]

# Amaç:
# product_text sütunundaki metni minimal düzeyde temizlemek.
# Birden fazla boşluğu tek boşluğa indirir ve baştaki/sondaki boşlukları kaldırır.
# Böylece ürün metni daha düzenli ve analiz için uygun hale gelir.

'Fragrance Discovery Set 19-69 Fragrance Value & Gift Sets Perfume Gift Sets Unisex/ Genderless Scent Warm &Spicy Scent Woody & Earthy Scent Fresh Scent Capri Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) D-Limonene, Linalool, Benzyl Salicylate, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Benzl Benzoate, Citral, Geraniol, Eugenol, Benzyl Alcohol, Farnesol, Citronellol, Isoeugenol. Invisible Post Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Benzyl Benzoate, Citral, Coumarin, Limonene, Alpha-Isomethyl Ionone, Linalool. Kashbah Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) Coumarin, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, D-Limonene, Eugenol, Linalool, Citronellol, Geraniol, Cinnamal, Citral. L’Air Barbes Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) Benzyl Salicylate, D-Limonene, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Linalool Citral, Alphaisomethyl Ionone, Benzyl Benzoate, Geraniol Farnesol, Isoeugenol, Eugenol. La Habana Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Benzyl Alcohol, Benzyl Benzoate, Benzyl Cinnamate, Cinnamal, Citral, Coumarin Limonene, Eugenol, Alpha-Isomethyl Ionone, Linalool. Purple Haze Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) Octoxynol-10, D-Limonene, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Geraniol, Linalool, Coumarin, Farnesol, Eugenol, Citral. Rainbow Bar Eau de Parfum: Alcohol Denat. (SD Alcohol 39C), Parfum (Fragrance) D-Limonene, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Hexyl Cinnamal, Citronellol, Linalool, Coumarin, Eugenol, Citral, Isoeugenol, Geraniol.'

In [18]:
import os

sorted([f for f in os.listdir("../data_raw") if f.endswith(".csv")])

# Amaç:
# data_raw klasöründeki tüm CSV dosyalarını listelemek.
# Özellikle review veri setinin kaç parçadan oluştuğunu görmek
# ve ileride birleştirilecek dosyaları doğrulamak için kullanılır.

['product_info.csv',
 'reviews_0-250.csv',
 'reviews_1250-end.csv',
 'reviews_250-500.csv',
 'reviews_500-750.csv',
 'reviews_750-1250.csv']

In [19]:
import pandas as pd

review_files = [
    "../data_raw/reviews_0-250.csv",
    "../data_raw/reviews_250-500.csv",
    "../data_raw/reviews_500-750.csv",
    "../data_raw/reviews_750-1250.csv",
    "../data_raw/reviews_1250-end.csv",
]

dfs = []
for path in review_files:
    df_part = pd.read_csv(path)
    print(path, df_part.shape)
    dfs.append(df_part)

reviews = pd.concat(dfs, ignore_index=True)

print("\nTOTAL reviews shape:", reviews.shape)
reviews.head(3)

# Amaç:
# Parçalar halinde verilen review veri setlerini okuyup tek bir DataFrame içinde birleştirmek.
# Kaggle veri seti çok büyük olduğu için reviews verisi birden fazla CSV dosyasına bölünmüştür.
# Bu adımda tüm parçalar okunur ve pd.concat ile tek bir reviews tablosu oluşturulur.

/var/folders/tm/wc8rn0xj05v33kkcby8sf0fm0000gn/T/ipykernel_7610/3163952926.py:13: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_part = pd.read_csv(path)

../data_raw/reviews_0-250.csv (602130, 19)
../data_raw/reviews_250-500.csv (206725, 19)
../data_raw/reviews_500-750.csv (116262, 19)

/var/folders/tm/wc8rn0xj05v33kkcby8sf0fm0000gn/T/ipykernel_7610/3163952926.py:13: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_part = pd.read_csv(path)
/var/folders/tm/wc8rn0xj05v33kkcby8sf0fm0000gn/T/ipykernel_7610/3163952926.py:13: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_part = pd.read_csv(path)

../data_raw/reviews_750-1250.csv (119317, 19)
../data_raw/reviews_1250-end.csv (49977, 19)

TOTAL reviews shape: (1094411, 19)

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [20]:
reviews.shape

(1094411, 19)

In [21]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094411 entries, 0 to 1094410
Data columns (total 19 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Unnamed: 0                1094411 non-null  int64
 1   author_id                 1094411 non-null  object
 2   rating                    1094411 non-null  int64
 3   is_recommended            926423 non-null   float64
 4   helpfulness               532819 non-null   float64
 5   total_feedback_count      1094411 non-null  int64
 6   total_neg_feedback_count  1094411 non-null  int64
 7   total_pos_feedback_count  1094411 non-null  int64
 8   submission_time           1094411 non-null  object
 9   review_text               1092967 non-null  object
 10  review_title              783757 non-null   object
 11  skin_tone                 923872 non-null   object
 12  eye_color                 884783 non-null   object
 13  skin_type                 982854 non-null   object
 14  hair_color                867643 non-null   object
 15  product_id                1094411 non-null  object
 16  product_name              1094411 non-null  object
 17  brand_name                1094411 non-null  object
 18  price_usd                 1094411 non-null  float64
dtypes: float64(3), int64(5), object(11)
memory usage: 158.6+ MB

In [22]:
# 1) Boyut ve kolonlar
print("reviews shape:", reviews.shape)
print("columns:", list(reviews.columns))

# 2) Zorunlu alanlarda null oranı
key_cols = ["author_id", "product_id", "rating"]
null_rates = reviews[key_cols].isna().mean().sort_values(ascending=False) * 100
print("\nNull % (key cols):")
print(null_rates)

# 3) Rating aralığı kontrol (boşları saymadan)
print("\nRating min/max (non-null):", reviews["rating"].dropna().min(), reviews["rating"].dropna().max())

# 4) Duplicate kontrolü (genel)
print("\nExact duplicate rows:", reviews.duplicated().sum())

# 5) Aynı kullanıcı-ürün birden fazla kez review atmış mı? (bu normal olabilir ama sayacağız)
dupe_user_item = reviews.duplicated(subset=["author_id", "product_id"], keep=False).sum()
print("Rows with duplicate (author_id, product_id):", dupe_user_item)

reviews shape: (1094411, 19)
columns: ['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness', 'total_feedback_count', 'total_neg_feedback_count', 'total_pos_feedback_count', 'submission_time', 'review_text', 'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color', 'product_id', 'product_name', 'brand_name', 'price_usd']

Null % (key cols):
author_id     0.0
product_id    0.0
rating        0.0
dtype: float64

Rating min/max (non-null): 1 5

Exact duplicate rows: 0
Rows with duplicate (author_id, product_id): 10471

In [23]:
reviews["submission_time"] = pd.to_datetime(reviews["submission_time"], errors="coerce")

# Amaç: submission_time sütununu string formatından datetime formatına dönüştürmek.
# errors="coerce" sayesinde geçersiz veya hatalı tarih değerleri NaT (eksik zaman) olarak işaretlenir.
# Böylece zaman bazlı analizler ve sıralamalar yapılabilir.

In [24]:
reviews = reviews.drop(columns=["Unnamed: 0"])

# Amaç: CSV dosyasından otomatik oluşan ve analizde kullanılmayacak olan
# "Unnamed: 0" indeks sütununu veri setinden kaldırmak.

In [25]:
reviews_clean = reviews.copy()

# Amaç: Orijinal reviews veri setini korumak için bir kopyasını oluşturmak.
# Bundan sonraki veri temizleme ve dönüşüm işlemleri reviews_clean üzerinde yapılacaktır.

In [26]:
import pandas as pd

# Güvenlik: sıralama için time null olursa sorun çıkmasın diye
reviews_clean["submission_time"] = pd.to_datetime(reviews_clean["submission_time"], errors="coerce")

# 0) Sadece CF için gerekli kolonları ayıralım (model bağımsız, çekirdek tablo)
cf_base = reviews_clean[["author_id", "product_id", "rating", "submission_time"]].copy()

# A) En güncel puan: son tarihi tut
cf_last = (
    cf_base.sort_values(["author_id", "product_id", "submission_time"])
          .drop_duplicates(subset=["author_id", "product_id"], keep="last")
)

# B) Ortalama puan: her user-item için rating ortalaması
cf_mean = (
    cf_base.groupby(["author_id", "product_id"], as_index=False)["rating"]
           .mean()
)
# İstersen yuvarlayabilirsin (ama şimdilik yuvarlama yok; karar sonra)
# cf_mean["rating"] = cf_mean["rating"].round(2)

# C) İlk puan: en eski tarihi tut
cf_first = (
    cf_base.sort_values(["author_id", "product_id", "submission_time"])
          .drop_duplicates(subset=["author_id", "product_id"], keep="first")
)

print("cf_base:", cf_base.shape)
print("cf_last:", cf_last.shape)
print("cf_mean:", cf_mean.shape)
print("cf_first:", cf_first.shape)

# Kaydet (interim)
cf_last.to_csv("../data_interim/reviews_cf_last.csv", index=False)
cf_mean.to_csv("../data_interim/reviews_cf_mean.csv", index=False)
cf_first.to_csv("../data_interim/reviews_cf_first.csv", index=False)

print("Saved: data_interim/reviews_cf_last.csv, reviews_cf_mean.csv, reviews_cf_first.csv")

# Amaç:
# Collaborative Filtering için gerekli olan user-item-rating tablosunu oluşturmak
# ve aynı kullanıcı aynı ürüne birden fazla puan verdiyse bunu farklı stratejilerle çözmek.
# Bu adımda üç alternatif CF veri seti hazırlanır:
# 1) en güncel puanı tutan tablo,
# 2) ortalama puanı alan tablo,
# 3) ilk puanı tutan tablo.
# Böylece model aşamasında farklı yaklaşımlar karşılaştırılabilir.

cf_base: (1094411, 4)
cf_last: (1088891, 4)
cf_mean: (1088891, 3)
cf_first: (1088891, 4)
Saved: data_interim/reviews_cf_last.csv, reviews_cf_mean.csv, reviews_cf_first.csv

In [27]:
products_clean.to_csv("../data_interim/products_clean.csv", index=False)
print("Saved: data_interim/products_clean.csv")

# Amaç:
# Temizlenmiş ve hazırlanmış ürün veri setini (products_clean) ara veri klasörüne kaydetmek.
# Böylece preprocessing adımlarını tekrar çalıştırmadan bu temiz veri seti daha sonra doğrudan kullanılabilir.

Saved: data_interim/products_clean.csv

In [28]:
reviews_profile = reviews_clean[
    ["product_id", "rating", "skin_type", "skin_tone", 
     "eye_color", "hair_color", "is_recommended"]
].copy()

print("Shape:", reviews_profile.shape)
reviews_profile.head()

# Amaç:
# Profil tabanlı öneri sistemi için gerekli kullanıcı özelliklerini içeren
# review kolonlarını ayırarak yeni bir veri seti (reviews_profile) oluşturmak.
# Bu tablo ürün puanı ile birlikte kullanıcı cilt tipi, ten tonu, göz ve saç rengi gibi
# özellikleri içerir ve ileride ürün-profili skorlarının hesaplanmasında kullanılacaktır.

Shape: (1094411, 7)

,product_id,rating,skin_type,skin_tone,eye_color,hair_color,is_recommended
0,P504322,5,dry,NaN,brown,black,1.0
1,P420652,1,NaN,NaN,NaN,NaN,0.0
2,P420652,5,dry,light,brown,blonde,1.0
3,P420652,5,combination,NaN,brown,black,1.0
4,P420652,5,combination,light,hazel,NaN,1.0

In [29]:
# Skin type boş olanları ayrı değerlendirebiliriz, ama şimdilik dahil etmiyoruz
reviews_profile_nonnull = reviews_profile.dropna(subset=["skin_type"])

product_skin_stats = (
    reviews_profile_nonnull
    .groupby(["product_id", "skin_type"])
    .agg(
        mean_rating=("rating", "mean"),
        review_count=("rating", "count"),
        recommend_rate=("is_recommended", "mean")
    )
    .reset_index()
)

product_skin_stats.head()

# Amaç:
# Skin type bilgisi bulunan review'ları kullanarak ürünlerin farklı cilt tipleri
# için nasıl performans gösterdiğini hesaplamak.
# Her product_id ve skin_type kombinasyonu için:
# - ortalama puan (mean_rating)
# - review sayısı (review_count)
# - önerilme oranı (recommend_rate)
# hesaplanarak product_skin_stats tablosu oluşturulur.

  product_id    skin_type  mean_rating  review_count  recommend_rate
0    P107306  combination     4.054054           111        0.756098
1    P107306          dry     4.450000            40        0.777778
2    P107306       normal     4.407407            27        0.750000
3    P107306         oily     2.772727            22        0.285714
4    P114902  combination     4.392381           525        0.865591

In [30]:
product_skin_pivot = (
    product_skin_stats
    .pivot(index="product_id", columns="skin_type", values="mean_rating")
    .reset_index()
)

product_skin_pivot.head()

# Amaç:
# product_skin_stats tablosunu pivot ederek her ürün için cilt tiplerine göre
# ortalama puanların ayrı sütunlarda yer aldığı bir tablo oluşturmak.
# Böylece her product_id için combination, dry, normal ve oily cilt tiplerine
# ait ortalama rating değerleri kolayca erişilebilir hale gelir.

skin_type product_id  combination       dry    normal      oily
0            P107306     4.054054  4.450000  4.407407  2.772727
1            P114902     4.392381  4.409091  4.527027  4.489960
2             P12045     4.482443  4.401575  4.423423  4.415385
3            P122651     4.406250  4.546667  4.818182  4.555556
4            P122661     4.472222  4.648352  4.684211  4.250000

In [31]:
# Global ortalama rating
global_mean = reviews_profile_nonnull["rating"].mean()

# m değeri (güven sabiti)
m = 20  # başlangıç için makul bir değer

product_skin_weighted = (
    reviews_profile_nonnull
    .groupby(["product_id", "skin_type"])
    .agg(
        mean_rating=("rating", "mean"),
        review_count=("rating", "count")
    )
    .reset_index()
)

# Düzeltilmiş skor hesapla
product_skin_weighted["weighted_score"] = (
    (product_skin_weighted["mean_rating"] * product_skin_weighted["review_count"] +
     global_mean * m)
    /
    (product_skin_weighted["review_count"] + m)
)

product_skin_weighted.head()

# Amaç:
# Ürünlerin cilt tipi bazındaki ortalama puanlarını, review sayısını da dikkate alarak
# daha güvenilir bir weighted_score ile düzeltmek.
# Bu yaklaşım, az sayıda review alan ürünlerin ortalama puanlarının yanıltıcı şekilde
# çok yüksek veya çok düşük görünmesini engeller.

  product_id    skin_type  mean_rating  review_count  weighted_score
0    P107306  combination     4.054054           111        4.091233
1    P107306          dry     4.450000            40        4.399191
2    P107306       normal     4.407407            27        4.360669
3    P107306         oily     2.772727            22        3.498844
4    P114902  combination     4.392381           525        4.388902

In [32]:
product_skin_weighted_pivot = (
    product_skin_weighted
    .pivot(index="product_id", columns="skin_type", values="weighted_score")
    .reset_index()
)

product_skin_weighted_pivot.head()

# Amaç:
# product_skin_weighted tablosunu pivot ederek her ürün için cilt tiplerine göre
# weighted_score değerlerini ayrı sütunlarda göstermek.
# Böylece her product_id için dry, oily, normal ve combination cilt tiplerine ait
# güvenilir skorlar tek satırda tutulur.

skin_type product_id  combination       dry    normal      oily
0            P107306     4.091233  4.399191  4.360669  3.498844
1            P114902     4.388902  4.383157  4.478207  4.475656
2             P12045     4.476965  4.393983  4.404210  4.399676
3            P122651     4.380375  4.494226  4.482305  4.377637
4            P122661     4.459380  4.585148  4.583785  4.262519

In [33]:
product_skin_count_pivot = (
    product_skin_weighted
    .pivot(index="product_id", columns="skin_type", values="review_count")
    .reset_index()
)

product_skin_count_pivot.head()

# Amaç:
# product_skin_weighted tablosundaki review_count değerlerini pivot ederek
# her ürün için cilt tiplerine göre kaç review bulunduğunu ayrı sütunlarda göstermek.
# Böylece combination, dry, normal ve oily cilt tipleri için review sayıları
# tek satırda ürün bazında tutulur.

skin_type product_id  combination    dry  normal   oily
0            P107306        111.0   40.0    27.0   22.0
1            P114902        525.0   66.0    74.0  249.0
2             P12045        655.0  254.0   111.0  130.0
3            P122651         64.0   75.0    11.0    9.0
4            P122661        252.0   91.0    57.0   56.0

In [34]:
product_skin_profile = product_skin_weighted.merge(
    product_skin_count_pivot,
    on="product_id",
    how="left",
    suffixes=("", "_count")
)

product_skin_profile.head()

# Amaç:
# Skin type bazlı weighted skor tablosunu, yine skin type bazlı review sayılarıyla birleştirmek.
# Böylece her ürün-cilt tipi satırında hem weighted_score bilgisi
# hem de ürünün tüm cilt tiplerindeki review sayıları birlikte görülebilir.

,product_id,skin_type,mean_rating,review_count,weighted_score,combination,dry,normal,oily
0,P107306,combination,4.054054,111,4.091233,111.0,40.0,27.0,22.0
1,P107306,dry,4.450000,40,4.399191,111.0,40.0,27.0,22.0
2,P107306,normal,4.407407,27,4.360669,111.0,40.0,27.0,22.0
3,P107306,oily,2.772727,22,3.498844,111.0,40.0,27.0,22.0
4,P114902,combination,4.392381,525,4.388902,525.0,66.0,74.0,249.0

In [35]:
product_skin_final = product_skin_weighted_pivot.merge(
    product_skin_count_pivot,
    on="product_id",
    how="left",
    suffixes=("_score", "_count")
)

product_skin_final.head()

# Skin type bazlı ürün skorları (product_skin_weighted_pivot) ile
# skin type bazlı review sayıları (product_skin_count_pivot) product_id üzerinden birleştirilir.
# Bu tablo profile-based recommendation aşamasında kullanılacak ürün-cilt tipi profilini temsil eder.

skin_type,product_id,combination_score,dry_score,normal_score,oily_score,combination_count,dry_count,normal_count,oily_count
0,P107306,4.091233,4.399191,4.360669,3.498844,111.0,40.0,27.0,22.0
1,P114902,4.388902,4.383157,4.478207,4.475656,525.0,66.0,74.0,249.0
2,P12045,4.476965,4.393983,4.404210,4.399676,655.0,254.0,111.0,130.0
3,P122651,4.380375,4.494226,4.482305,4.377637,64.0,75.0,11.0,9.0
4,P122661,4.459380,4.585148,4.583785,4.262519,252.0,91.0,57.0,56.0

In [36]:
# skin_tone boş olanları bu analizde kullanmayacağız
reviews_tone = reviews_clean[["product_id", "rating", "skin_tone", "is_recommended"]].copy()
reviews_tone = reviews_tone.dropna(subset=["skin_tone"])

global_mean_tone = reviews_tone["rating"].mean()
m = 20  # temkinli sistem sabiti (aynı)

product_tone_weighted = (
    reviews_tone
    .groupby(["product_id", "skin_tone"])
    .agg(
        mean_rating=("rating", "mean"),
        review_count=("rating", "count"),
        recommend_rate=("is_recommended", "mean")
    )
    .reset_index()
)

product_tone_weighted["weighted_score"] = (
    (product_tone_weighted["mean_rating"] * product_tone_weighted["review_count"] +
     global_mean_tone * m)
    /
    (product_tone_weighted["review_count"] + m)
)

product_tone_weighted.head()

# Amaç:
# Skin tone bilgisi bulunan review’ları kullanarak ürünlerin farklı ten tonlarında
# nasıl performans gösterdiğini hesaplamak.
# Her product_id ve skin_tone kombinasyonu için:
# - ortalama puan (mean_rating)
# - review sayısı (review_count)
# - önerilme oranı (recommend_rate)
# hesaplanır ve daha sonra güvenilirliği artırmak için weighted_score üretilir.

,product_id,skin_tone,mean_rating,review_count,recommend_rate,weighted_score
0,P107306,dark,1.000000,1,0.000000,4.138173
1,P107306,deep,3.666667,3,0.666667,4.213115
2,P107306,fair,4.190476,42,0.750000,4.224220
3,P107306,fairLight,3.500000,4,0.500000,4.162568
4,P107306,light,4.375000,48,0.722222,4.351495

In [37]:
# 1) Tone skor pivot
product_tone_score_pivot = (
    product_tone_weighted
    .pivot(index="product_id", columns="skin_tone", values="weighted_score")
    .reset_index()
)

# 2) Tone count pivot
product_tone_count_pivot = (
    product_tone_weighted
    .pivot(index="product_id", columns="skin_tone", values="review_count")
    .reset_index()
)

# Kolon isimlerini ayırt edelim
product_tone_score_pivot = product_tone_score_pivot.rename(
    columns={c: f"{c}_tone_score" for c in product_tone_score_pivot.columns if c != "product_id"}
)
product_tone_count_pivot = product_tone_count_pivot.rename(
    columns={c: f"{c}_tone_count" for c in product_tone_count_pivot.columns if c != "product_id"}
)

# 3) Hepsini product_id üzerinden birleştir
product_profile = (
    product_skin_final
    .merge(product_tone_score_pivot, on="product_id", how="left")
    .merge(product_tone_count_pivot, on="product_id", how="left")
)

print("product_profile shape:", product_profile.shape)
product_profile.head()

# Amaç:
# Skin tone bazlı weighted skorları ve review sayılarını pivot ederek ürün seviyesine taşımak
# ve bunları skin type bazlı ürün profil tablosu ile birleştirerek nihai product_profile
# tablosunu oluşturmak.
# Bu tablo, her ürün için farklı kullanıcı özelliklerine (skin_type ve skin_tone)
# göre performans skorlarını ve veri yoğunluğunu içerir.

product_profile shape: (2350, 37)

,product_id,combination_score,dry_score,normal_score,oily_score,combination_count,dry_count,normal_count,oily_count,dark_tone_score,...,fairLight_tone_count,light_tone_count,lightMedium_tone_count,medium_tone_count,mediumTan_tone_count,notSureST_tone_count,olive_tone_count,porcelain_tone_count,rich_tone_count,tan_tone_count
0,P107306,4.091233,4.399191,4.360669,3.498844,111.0,40.0,27.0,22.0,4.138173,...,4.0,48.0,39.0,9.0,16.0,NaN,1.0,1.0,NaN,2.0
1,P114902,4.388902,4.383157,4.478207,4.475656,525.0,66.0,74.0,249.0,NaN,...,20.0,296.0,205.0,26.0,82.0,NaN,NaN,NaN,NaN,38.0
2,P12045,4.476965,4.393983,4.404210,4.399676,655.0,254.0,111.0,130.0,NaN,...,72.0,308.0,219.0,75.0,75.0,1.0,NaN,1.0,2.0,53.0
3,P122651,4.380375,4.494226,4.482305,4.377637,64.0,75.0,11.0,9.0,NaN,...,3.0,39.0,33.0,3.0,12.0,NaN,NaN,NaN,NaN,2.0
4,P122661,4.459380,4.585148,4.583785,4.262519,252.0,91.0,57.0,56.0,NaN,...,6.0,180.0,101.0,5.0,46.0,NaN,NaN,NaN,1.0,15.0

In [38]:
# ------------------------------------------------------------------
# PROFILE-BASED RECOMMENDATION FONKSİYONU
#
# Bu fonksiyon, kullanıcının profil bilgilerine göre ürün önerir.
#
# Kullanılan kullanıcı özellikleri:
# - skin_type  → kullanıcının cilt tipi (dry, oily, combination, normal)
# - skin_tone  → kullanıcının ten rengi
# - category   → kullanıcının aradığı ürün kategorisi (tertiary_category)
#
# Sistem şu mantıkla çalışır:
# 1) Önce ürünleri kategoriye göre filtreler
# 2) Kullanıcının skin_type için hesaplanmış ürün skorunu alır
# 3) Kullanıcının skin_tone için hesaplanmış ürün skorunu alır
# 4) Bu skorları birleştirerek final recommendation score oluşturur
# 5) En yüksek skora sahip ürünleri önerir
#
# top_n → kaç ürün önerileceğini belirler
# ------------------------------------------------------------------

def recommend_products(
    skin_type,
    skin_tone,
    category,
    top_n=10
):
    pass

In [39]:
# ------------------------------------------------------------------
# PROFILE-BASED + FALLBACK RECOMMENDATION FONKSİYONU
#
# Bu fonksiyon, kullanıcının profil bilgilerine göre ürün önerir.
#
# Ana mantık:
# 1) Önce ürünleri product_profile tablosundan kategoriye göre filtreler
# 2) Eğer bu kategoride profile-based skor üretilebilen ürün varsa:
#       - skin_type ve skin_tone skorlarını kullanır
#       - dinamik ağırlıklarla final profile_score hesaplar
# 3) Eğer profile-based ürün yoksa:
#       - products_clean içinden aynı kategorideki ürünleri alır
#       - rating, reviews ve loves_count ile fallback skor üretir
#
# Böylece sistem bazı kategorilerde profile verisi olmasa bile
# öneri üretebilir.
# ------------------------------------------------------------------

def recommend_products(
    skin_type,
    skin_tone,
    category,
    top_n=10
):
    import numpy as np

    # ---------------------------------------------------------------
    # 1) Ürün profil tablosu ile temiz ürün tablosunu birleştir
    # ---------------------------------------------------------------
    df = product_profile.merge(
        products_clean,
        on="product_id",
        how="left"
    )

    # ---------------------------------------------------------------
    # 2) Kategoriye göre filtrele
    # contains kullanıyoruz çünkü kategori adı daha uzun olabilir
    # Örn: "Under-Eye Concealer" içinde "concealer" geçer
    # ---------------------------------------------------------------
    df = df[
        df["tertiary_category"]
        .fillna("")
        .str.lower()
        .str.contains(category.lower(), na=False)
    ]

    # ---------------------------------------------------------------
    # 3) Eğer product_profile içinde bu kategori yoksa
    # fallback recommendation çalıştır
    # ---------------------------------------------------------------
    if df.shape[0] == 0:
        print("Profile-based veri bulunamadı. Fallback recommendation çalışıyor...")

        fallback_df = products_clean[
            products_clean["tertiary_category"]
            .fillna("")
            .str.lower()
            .str.contains(category.lower(), na=False)
        ].copy()

        if fallback_df.shape[0] == 0:
            print("Bu kategori için ürün bulunamadı.")
            return None

        # -----------------------------------------------------------
        # Fallback skor:
        # rating, reviews ve loves_count bilgilerini kullanıyoruz
        # Eksik değerleri güvenli şekilde dolduruyoruz
        # -----------------------------------------------------------
        fallback_df["rating"] = fallback_df["rating"].fillna(0)
        fallback_df["reviews"] = fallback_df["reviews"].fillna(0)
        fallback_df["loves_count"] = fallback_df["loves_count"].fillna(0)

        # log1p: büyük loves_count değerlerini yumuşatmak için
        fallback_df["fallback_score"] = (
            0.5 * fallback_df["rating"] +
            0.3 * np.log1p(fallback_df["reviews"]) +
            0.2 * np.log1p(fallback_df["loves_count"])
        )

        fallback_df = fallback_df.sort_values("fallback_score", ascending=False)

        result_cols = [
            "product_id",
            "product_name",
            "brand_name",
            "primary_category",
            "secondary_category",
            "tertiary_category",
            "price_usd",
            "rating",
            "reviews",
            "loves_count",
            "fallback_score"
        ]

        result_cols = [col for col in result_cols if col in fallback_df.columns]

        return fallback_df[result_cols].head(top_n)

    # ---------------------------------------------------------------
    # 4) Kullanıcının profiline göre ilgili skor ve count sütunlarını seç
    # Örn:
    # skin_type = dry   -> dry_score, dry_count
    # skin_tone = light -> light_tone_score, light_tone_count
    # ---------------------------------------------------------------
    type_score_col = f"{skin_type.lower()}_score"
    type_count_col = f"{skin_type.lower()}_count"

    tone_score_col = f"{skin_tone}_tone_score"
    tone_count_col = f"{skin_tone}_tone_count"

    if type_score_col not in df.columns:
        print(f"Cilt tipi için uygun skor sütunu bulunamadı: {type_score_col}")
        return None

    if tone_score_col not in df.columns:
        print(f"Ten tonu için uygun skor sütunu bulunamadı: {tone_score_col}")
        return None

    # ---------------------------------------------------------------
    # 5) İlgili skor ve count sütunlarını standart isimlerle kopyala
    # ---------------------------------------------------------------
    df["type_score"] = df[type_score_col]
    df["type_count"] = df[type_count_col]

    df["tone_score"] = df[tone_score_col]
    df["tone_count"] = df[tone_count_col]

    # ---------------------------------------------------------------
    # 6) Dinamik ağırlık hesaplama
    #
    # Mantık:
    # - Veri sayısı yüksek olan profile sinyaline daha çok güven
    # - Ancak count çok büyükse sistemi domine etmesin diye sqrt kullan
    # - Başlangıçta skin_type daha önemli kabul ediliyor
    # ---------------------------------------------------------------
    type_strength = np.sqrt(df["type_count"].fillna(0))
    tone_strength = np.sqrt(df["tone_count"].fillna(0))

    base_type_weight = 0.7
    base_tone_weight = 0.3

    weighted_type_strength = base_type_weight * type_strength
    weighted_tone_strength = base_tone_weight * tone_strength

    total_strength = weighted_type_strength + weighted_tone_strength
    total_strength = total_strength.replace(0, 1)

    df["dynamic_type_weight"] = weighted_type_strength / total_strength
    df["dynamic_tone_weight"] = weighted_tone_strength / total_strength

    # Eğer skor eksikse o özelliğin ağırlığını sıfırla
    df.loc[df["type_score"].isna(), "dynamic_type_weight"] = 0
    df.loc[df["tone_score"].isna(), "dynamic_tone_weight"] = 0

    # Ağırlıkları tekrar normalize et
    weight_sum = df["dynamic_type_weight"] + df["dynamic_tone_weight"]
    weight_sum = weight_sum.replace(0, 1)

    df["dynamic_type_weight"] = df["dynamic_type_weight"] / weight_sum
    df["dynamic_tone_weight"] = df["dynamic_tone_weight"] / weight_sum

    # ---------------------------------------------------------------
    # 7) Final profile score hesapla
    # ---------------------------------------------------------------
    df["profile_score"] = (
        df["dynamic_type_weight"] * df["type_score"].fillna(0) +
        df["dynamic_tone_weight"] * df["tone_score"].fillna(0)
    )

    # ---------------------------------------------------------------
    # 8) Ürünleri final profile_score'a göre sırala
    # ---------------------------------------------------------------
    df = df.sort_values("profile_score", ascending=False)

    # ---------------------------------------------------------------
    # 9) Sonuç tablosunda gösterilecek sütunları seç
    # ---------------------------------------------------------------
    result_cols = [
        "product_id",
        "product_name",
        "brand_name",
        "primary_category",
        "secondary_category",
        "tertiary_category",
        "price_usd",
        "type_score",
        "tone_score",
        "dynamic_type_weight",
        "dynamic_tone_weight",
        "profile_score"
    ]

    result_cols = [col for col in result_cols if col in df.columns]

    return df[result_cols].head(top_n)

In [40]:
# ---------------------------------------------------------------
# Örnek kullanım
# Kullanıcı profili:
# - skin_type: dry
# - skin_tone: light
# - category: Concealer
# ---------------------------------------------------------------

recommendations = recommend_products(
    skin_type="dry",
    skin_tone="light",
    category="Concealer",
    top_n=10
)

recommendations

Profile-based veri bulunamadı. Fallback recommendation çalışıyor...

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,fallback_score
5249,P377873,Radiant Creamy Concealer,NARS,Makeup,Face,Concealer,32.0,4.3080,12887.0,1153594,7.784894
7844,P432298,Born This Way Super Coverage Multi-Use Longwea...,Too Faced,Makeup,Face,Concealer,34.0,4.3390,4230.0,501464,7.299616
5253,P416200,Soft Matte Complete Concealer,NARS,Makeup,Face,Concealer,32.0,4.4704,2668.0,412271,7.187925
8431,P218431,Touche Éclat All-Over Brightening Concealer Pen,Yves Saint Laurent,Makeup,Face,Concealer,40.0,4.3344,4360.0,193037,7.115465
3334,P500309,#FauxFilter Luminous Matte Buildable Coverage ...,HUDA BEAUTY,Makeup,Face,Concealer,31.0,4.6880,3596.0,98661,7.100248
4710,P151107,Full Cover Concealer,MAKE UP FOR EVER,Makeup,Face,Concealer,34.0,4.3574,4885.0,120132,7.066210
4224,P456151,Revealer Super Creamy + Brightening Concealer ...,Kosas,Makeup,Face,Concealer,30.0,3.9914,2910.0,513855,7.018515
4357,P473717,Teint Idole Ultra Wear All Over Full Coverage ...,Lancôme,Makeup,Face,Concealer,29.0,4.5854,3427.0,79019,6.990111
545,P448162,Boi-ing Cakeless Full Coverage Waterproof Liqu...,Benefit Cosmetics,Makeup,Face,Concealer,27.0,4.3136,6681.0,50440,6.964664
646,P270555,Under Eye Corrector,Bobbi Brown,Makeup,Face,Concealer,33.0,4.4694,2499.0,113987,6.910683

In [41]:
print(type(product_profile))
print(product_profile.shape)

<class 'pandas.core.frame.DataFrame'>
(2350, 37)

In [42]:
# ---------------------------------------------------------------
# "con" ile başlayan veya içinde "conce" geçen kategori isimlerini ara
# Böylece dataset'te kapatıcı kategorisinin nasıl yazıldığını bulabiliriz
# ---------------------------------------------------------------

[
    cat for cat in products_clean["tertiary_category"].dropna().unique()
    if "conce" in cat.lower()
]

['Concealer', 'Under-Eye Concealer']

In [43]:
# products_clean içinde Concealer geçen ürünleri say
products_clean[
    products_clean["tertiary_category"]
    .fillna("")
    .str.lower()
    .str.contains("concealer", na=False)
].shape

(87, 19)

In [44]:
# product_profile ile products_clean birleşince Concealer sayısı kaç?
merged_df = product_profile.merge(
    products_clean,
    on="product_id",
    how="left"
)

merged_df[
    merged_df["tertiary_category"]
    .fillna("")
    .str.lower()
    .str.contains("concealer", na=False)
].shape

(0, 55)

In [45]:
merged_df["tertiary_category"].dropna().value_counts().head(50)

tertiary_category
Moisturizers                 377
Face Serums                  368
Face Wash & Cleansers        213
Eye Creams & Treatments      170
Face Masks                   134
Face Sunscreen                95
Toners                        77
Face Oils                     66
Mists & Essences              63
Facial Peels                  49
Anti-Aging                    47
Beauty Supplements            44
Exfoliators                   41
Blemish & Acne Treatments     35
For Body                      34
Sheet Masks                   31
Facial Rollers                25
For Face                      18
Night Creams                  17
Eye Masks                     14
Facial Cleansing Brushes      13
Decollete & Neck Creams       10
Body Sunscreen                10
Holistic Wellness             10
Hair Removal                   9
Makeup Removers                9
Face Wipes                     6
Teeth Whitening                5
BB & CC Creams                 4
Blotting Papers                4
Name: count, dtype: int64

In [46]:
products_clean.columns

Index(['product_id', 'product_name', 'brand_name', 'loves_count', 'rating',
       'reviews', 'ingredients', 'price_usd', 'limited_edition', 'new',
       'online_only', 'out_of_stock', 'sephora_exclusive', 'highlights',
       'primary_category', 'secondary_category', 'tertiary_category',
       'child_count', 'product_text'],
      dtype='object')

In [47]:
"product_text" in products_clean.columns

True

In [48]:
products_clean["product_text"].head(3)

0    Fragrance Discovery Set 19-69 Fragrance Value ...
1    La Habana Eau de Parfum 19-69 Fragrance Women ...
2    Rainbow Bar Eau de Parfum 19-69 Fragrance Wome...
Name: product_text, dtype: object

In [49]:
# ---------------------------------------------------------------
# CONTENT-BASED RECOMMENDATION MODEL
#
# Bu model ürünlerin metin içeriklerini kullanarak
# birbirine benzer ürünleri bulur.
#
# product_text sütunu şu bilgileri içerir:
# - product_name
# - brand_name
# - category bilgileri
# - highlights / ingredients
#
# Bu metinler TF-IDF ile sayısal vektörlere çevrilir.
# Daha sonra cosine similarity ile ürün benzerliği hesaplanır.
# ---------------------------------------------------------------

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
# ---------------------------------------------------------------
# TF-IDF VECTORIZATION
#
# product_text sütununu sayısal vektörlere dönüştürüyoruz.
# Böylece her ürün bir feature vektörü haline geliyor.
# ---------------------------------------------------------------

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

tfidf_matrix = tfidf.fit_transform(products_clean["product_text"])

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (8494, 5000)

In [51]:
# ---------------------------------------------------------------
# COSINE SIMILARITY MATRIX
#
# Bu adımda tüm ürünler arasındaki benzerliği hesaplıyoruz.
# Her ürün diğer tüm ürünlerle karşılaştırılır.
#
# Sonuç:
# similarity_matrix[i][j]
# → ürün i ile ürün j ne kadar benzer
# ---------------------------------------------------------------

similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (8494, 8494)

In [52]:
similarity_matrix = cosine_similarity(tfidf_matrix)
print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (8494, 8494)

In [53]:
# ---------------------------------------------------------------
# CONTENT-BASED RECOMMENDATION FUNCTION
#
# Bu fonksiyon verilen bir ürüne en benzer ürünleri bulur.
#
# Çıktıya özellikle şu alanları ekliyoruz:
# - product_id
# - similarity_score
#
# Çünkü hybrid recommendation aşamasında content skoru ile
# collaborative filtering skorunu product_id üzerinden birleştireceğiz.
# ---------------------------------------------------------------

def recommend_similar_products(product_name, top_n=10):

    # -----------------------------------------------------------
    # 1) Ürünün dataset içindeki index'ini bul
    # -----------------------------------------------------------
    matches = products_clean[
        products_clean["product_name"].str.lower().str.contains(product_name.lower(), na=False)
    ]

    if matches.shape[0] == 0:
        print("Ürün bulunamadı.")
        return None

    product_index = matches.index[0]

    # -----------------------------------------------------------
    # 2) Bu ürünün similarity skorlarını al
    # -----------------------------------------------------------
    similarity_scores = list(enumerate(similarity_matrix[product_index]))

    # -----------------------------------------------------------
    # 3) En yüksek benzerlik skorlarına göre sırala
    # -----------------------------------------------------------
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # İlk eleman ürünün kendisi olduğu için atlıyoruz
    similarity_scores = similarity_scores[1:top_n+1]

    # -----------------------------------------------------------
    # 4) Benzer ürünlerin indexlerini ve similarity skorlarını al
    # -----------------------------------------------------------
    product_indices = [i[0] for i in similarity_scores]
    sim_scores = [i[1] for i in similarity_scores]

    # -----------------------------------------------------------
    # 5) Sonuç tablosu
    # product_id ve similarity_score özellikle ekleniyor
    # -----------------------------------------------------------
    result = products_clean.iloc[product_indices][
        [
            "product_id",
            "product_name",
            "brand_name",
            "primary_category",
            "secondary_category",
            "tertiary_category",
            "price_usd",
            "rating",
            "reviews",
            "loves_count"
        ]
    ].copy()

    result["similarity_score"] = sim_scores

    return result

In [54]:
recommend_similar_products("Radiant Creamy Concealer", top_n=10)

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,similarity_score
5251,P422077,Mini Radiant Creamy Concealer,NARS,Mini Size,Makeup,NaN,15.0,4.1253,1708.0,444366,0.874305
5309,P505043,Mini Radiant Creamy Concealer and Afterglow Li...,NARS,Makeup,Value & Gift Sets,NaN,25.0,NaN,NaN,2535,0.690995
6817,P449107,Synchro Skin Self-Refreshing Concealer,Shiseido,Makeup,Face,Concealer,31.0,4.4394,1311.0,38828,0.594693
5287,P473173,Radiant Creamy Liquid Color Corrector,NARS,Makeup,Face,Color Correct,30.0,3.5045,111.0,28551,0.553201
5264,P462720,Soft Matte Complete Foundation,NARS,Makeup,Face,Foundation,42.0,4.1135,1851.0,152923,0.538023
5253,P416200,Soft Matte Complete Concealer,NARS,Makeup,Face,Concealer,32.0,4.4704,2668.0,412271,0.537174
7025,P440044,Studio Skin Flawless Oil-Free 24 Hour Concealer,Smashbox,Makeup,Face,Concealer,29.0,4.3951,739.0,25465,0.526362
1449,P122914,"Airbrush Concealer Illuminates, Perfects",CLINIQUE,Makeup,Face,Concealer,28.0,4.1732,462.0,20466,0.516906
1902,P482262,Backstage Concealer,Dior,Makeup,Face,Concealer,29.0,4.4750,1341.0,146408,0.506883
444,P470512,Original Liquid Mineral Concealer,bareMinerals,Makeup,Face,Concealer,28.0,4.3244,706.0,15997,0.497470

In [55]:
recommend_similar_products("Born This Way", top_n=10)

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,similarity_score
6476,P500453,Best Skin Ever Full Coverage Multi-Use Concealer,SEPHORA COLLECTION,Makeup,Face,Concealer,15.0,4.3443,366.0,59835,0.678274
7868,P458586,Born This Way Matte Longwear Liquid Foundation,Too Faced,Makeup,Face,Foundation,45.0,4.2657,1035.0,48195,0.620939
7857,P455201,Born This Way The Natural Nudes Eyeshadow Palette,Too Faced,Makeup,Eye,Eye Palettes,52.0,3.9965,286.0,104823,0.547204
7904,P505386,Born This Way Healthy Glow Spf 30 Moisturizing...,Too Faced,Makeup,Face,Foundation,42.0,NaN,NaN,1020,0.523566
7845,P397517,Born This Way Natural Finish Longwear Liquid F...,Too Faced,Makeup,Face,Foundation,45.0,4.0437,14882.0,465412,0.521083
7876,P484079,Born This Way Ethereal Light Smoothing Concealer,Too Faced,Makeup,Face,Concealer,26.0,4.2849,516.0,34712,0.512096
7893,P501013,Born This Way Ethereal Setting Powder,Too Faced,Makeup,Face,Setting Spray & Powder,38.0,4.4699,581.0,8405,0.508747
7881,P483500,Born This Way Sunset Stripped Eyeshadow Palette,Too Faced,Makeup,Eye,Eye Palettes,52.0,4.5430,291.0,21960,0.494343
4723,P460729,Matte Velvet Skin High Coverage Multi-Use Conc...,MAKE UP FOR EVER,Makeup,Face,Concealer,30.0,4.3733,584.0,39326,0.457755
670,P501412,Skin Full Cover Concealer,Bobbi Brown,Makeup,Face,Concealer,33.0,4.6893,1429.0,17491,0.455311

In [56]:
recommend_similar_products("Radiant Creamy Concealer")

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,similarity_score
5251,P422077,Mini Radiant Creamy Concealer,NARS,Mini Size,Makeup,NaN,15.0,4.1253,1708.0,444366,0.874305
5309,P505043,Mini Radiant Creamy Concealer and Afterglow Li...,NARS,Makeup,Value & Gift Sets,NaN,25.0,NaN,NaN,2535,0.690995
6817,P449107,Synchro Skin Self-Refreshing Concealer,Shiseido,Makeup,Face,Concealer,31.0,4.4394,1311.0,38828,0.594693
5287,P473173,Radiant Creamy Liquid Color Corrector,NARS,Makeup,Face,Color Correct,30.0,3.5045,111.0,28551,0.553201
5264,P462720,Soft Matte Complete Foundation,NARS,Makeup,Face,Foundation,42.0,4.1135,1851.0,152923,0.538023
5253,P416200,Soft Matte Complete Concealer,NARS,Makeup,Face,Concealer,32.0,4.4704,2668.0,412271,0.537174
7025,P440044,Studio Skin Flawless Oil-Free 24 Hour Concealer,Smashbox,Makeup,Face,Concealer,29.0,4.3951,739.0,25465,0.526362
1449,P122914,"Airbrush Concealer Illuminates, Perfects",CLINIQUE,Makeup,Face,Concealer,28.0,4.1732,462.0,20466,0.516906
1902,P482262,Backstage Concealer,Dior,Makeup,Face,Concealer,29.0,4.4750,1341.0,146408,0.506883
444,P470512,Original Liquid Mineral Concealer,bareMinerals,Makeup,Face,Concealer,28.0,4.3244,706.0,15997,0.497470

In [57]:
# ------------------------------------------------------------------
# COLLABORATIVE FILTERING İÇİN ANA VERİ SETİNİ YÜKLEME
#
# Bu adımda daha önce preprocessing aşamasında oluşturulan
# reviews_cf_last.csv dosyasını yüklüyoruz.
#
# Bu tablo:
# - author_id  -> kullanıcı
# - product_id -> ürün
# - rating     -> puan
# - submission_time -> en güncel review zamanı
#
# Aynı kullanıcı aynı ürüne birden fazla review verdiyse,
# bu tabloda sadece en güncel review tutulmuştur.
# ------------------------------------------------------------------

cf_data = pd.read_csv("../data_interim/reviews_cf_last.csv")

print("CF data shape:", cf_data.shape)
cf_data.head()

CF data shape: (1088891, 4)

/var/folders/tm/wc8rn0xj05v33kkcby8sf0fm0000gn/T/ipykernel_7610/775128398.py:17: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  cf_data = pd.read_csv("../data_interim/reviews_cf_last.csv")

  author_id product_id  rating submission_time
0    538863    P420652       1      2018-11-01
1    549704    P218700       5      2011-04-21
2    557770    P232903       5      2016-02-19
3    561736    P421998       5      2018-07-28
4    561736    P445951       5      2018-07-28

In [58]:
# ------------------------------------------------------------------
# CF VERİ SETİNİN TEMEL YAPISINI İNCELEME
#
# Bu adımda:
# - kaç benzersiz kullanıcı var
# - kaç benzersiz ürün var
# - toplam rating sayısı kaç
# bunları inceliyoruz.
# ------------------------------------------------------------------

n_users = cf_data["author_id"].nunique()
n_items = cf_data["product_id"].nunique()
n_ratings = len(cf_data)

print("Benzersiz kullanıcı sayısı:", n_users)
print("Benzersiz ürün sayısı:", n_items)
print("Toplam rating sayısı:", n_ratings)

Benzersiz kullanıcı sayısı: 506517
Benzersiz ürün sayısı: 2351
Toplam rating sayısı: 1088891

In [59]:
# ------------------------------------------------------------------
# SPARSITY (SEYREKLİK) HESAPLAMA
#
# User-item matrisi çoğunlukla boş olur.
# Bu yüzden CF veri setinin ne kadar seyrek olduğunu hesaplıyoruz.
#
# sparsity = 1 - (mevcut rating sayısı / tüm olası user-item çiftleri)
# ------------------------------------------------------------------

sparsity = 1 - (n_ratings / (n_users * n_items))

print("Sparsity:", round(sparsity, 4))
print("Sparsity (%):", round(sparsity * 100, 2))

Sparsity: 0.9991
Sparsity (%): 99.91

In [60]:
# ------------------------------------------------------------------
# USER VE ITEM INDEX MAPPING
#
# CF algoritmalarında kullanıcı ve ürün ID'lerini doğrudan string/object
# olarak kullanmak yerine, bunları integer index'e çeviriyoruz.
#
# Amaç:
# - sparse matrix oluşturabilmek
# - her kullanıcıya ve ürüne bir satır/sütun numarası vermek
# ------------------------------------------------------------------

user_ids = cf_data["author_id"].unique()
item_ids = cf_data["product_id"].unique()

user_to_idx = {user_id: idx for idx, user_id in enumerate(user_ids)}
item_to_idx = {item_id: idx for idx, item_id in enumerate(item_ids)}

idx_to_user = {idx: user_id for user_id, idx in user_to_idx.items()}
idx_to_item = {idx: item_id for item_id, idx in item_to_idx.items()}

print("Toplam kullanıcı:", len(user_to_idx))
print("Toplam ürün:", len(item_to_idx))

Toplam kullanıcı: 506517
Toplam ürün: 2351

In [61]:
# ------------------------------------------------------------------
# USER VE ITEM INDEX KOLONLARI
#
# Her rating kaydını:
# - user_idx
# - item_idx
# şeklinde sayısal index'lere çeviriyoruz.
# ------------------------------------------------------------------

cf_data["user_idx"] = cf_data["author_id"].map(user_to_idx)
cf_data["item_idx"] = cf_data["product_id"].map(item_to_idx)

cf_data[["author_id", "product_id", "user_idx", "item_idx", "rating"]].head()

  author_id product_id  user_idx  item_idx  rating
0    538863    P420652         0         0       1
1    549704    P218700         1         1       5
2    557770    P232903         2         2       5
3    561736    P421998         3         3       5
4    561736    P445951         3         4       5

In [62]:
# ------------------------------------------------------------------
# SPARSE USER-ITEM MATRIX
#
# Bu matriste:
# - satırlar kullanıcıları
# - sütunlar ürünleri
# - hücreler rating değerlerini temsil eder
#
# Veri çok seyrek olduğu için scipy'nin sparse matrix yapısını kullanıyoruz.
# ------------------------------------------------------------------

from scipy.sparse import csr_matrix

user_item_matrix = csr_matrix(
    (
        cf_data["rating"],
        (cf_data["user_idx"], cf_data["item_idx"])
    ),
    shape=(len(user_to_idx), len(item_to_idx))
)

print("User-item matrix shape:", user_item_matrix.shape)
print("Non-zero entries (rating sayısı):", user_item_matrix.nnz)

User-item matrix shape: (506517, 2351)
Non-zero entries (rating sayısı): 1088886

In [63]:
# ------------------------------------------------------------------
# TRUNCATED SVD İLE LATENT FACTOR ÇIKARMA
#
# Amaç:
# User-item matrisini daha düşük boyutlu latent faktörlere indirgemek.
#
# Bu yaklaşım klasik collaborative filtering mantığına uygundur:
# - benzer kullanıcı davranışlarını öğrenir
# - benzer ürün yapılarını öğrenir
# - seyrek matriste çalışabilir
# ------------------------------------------------------------------

from sklearn.decomposition import TruncatedSVD

n_factors = 50  # başlangıç için makul latent factor sayısı

svd = TruncatedSVD(n_components=n_factors, random_state=42)
user_factors = svd.fit_transform(user_item_matrix)
item_factors = svd.components_.T

print("User latent matrix shape:", user_factors.shape)
print("Item latent matrix shape:", item_factors.shape)

User latent matrix shape: (506517, 50)
Item latent matrix shape: (2351, 50)

In [64]:
# ------------------------------------------------------------------
# TAHMİNİ USER-ITEM SKOR MATRİSİ
#
# Kullanıcı latent vektörleri ile ürün latent vektörlerini çarparak
# tahmini skor matrisi oluşturuyoruz.
#
# predicted_scores[user, item]
# → o kullanıcı için o ürünün tahmini skoru
# ------------------------------------------------------------------

predicted_scores = user_factors @ item_factors.T

print("Predicted score matrix shape:", predicted_scores.shape)

Predicted score matrix shape: (506517, 2351)

In [65]:
# ------------------------------------------------------------------
# COLLABORATIVE FILTERING RECOMMENDATION FUNCTION
#
# Bu fonksiyon belirli bir kullanıcı için henüz puan vermediği ürünleri
# tahmini skora göre sıralar ve en iyi top_n ürünü önerir.
# ------------------------------------------------------------------

def recommend_cf_products(author_id, top_n=10):
    # Kullanıcı veri setinde yoksa bilgi ver
    if author_id not in user_to_idx:
        print("Bu kullanıcı CF veri setinde bulunamadı.")
        return None

    user_idx = user_to_idx[author_id]

    # Kullanıcının tahmini skorlarını al
    user_scores = predicted_scores[user_idx]

    # Kullanıcının daha önce puan verdiği ürünleri bul
    rated_items = set(
        cf_data.loc[cf_data["author_id"] == author_id, "product_id"].values
    )

    # Tüm ürünler için skor tablosu oluştur
    rec_df = pd.DataFrame({
        "product_id": item_ids,
        "cf_score": user_scores
    })

    # Daha önce puan verilen ürünleri çıkar
    rec_df = rec_df[~rec_df["product_id"].isin(rated_items)]

    # Ürün bilgileri ile birleştir
    rec_df = rec_df.merge(
        products_clean,
        on="product_id",
        how="left"
    )

    # En yüksek skorlu ürünleri sırala
    rec_df = rec_df.sort_values("cf_score", ascending=False)

    result_cols = [
        "product_id",
        "product_name",
        "brand_name",
        "primary_category",
        "secondary_category",
        "tertiary_category",
        "price_usd",
        "rating",
        "reviews",
        "loves_count",
        "cf_score"
    ]

    result_cols = [col for col in result_cols if col in rec_df.columns]

    return rec_df[result_cols].head(top_n)

In [66]:
# ------------------------------------------------------------------
# TEST İÇİN UYGUN BİR KULLANICI SEÇME
#
# Kullanıcı başına rating sayısını hesaplıyoruz.
# Böylece CF modelinin anlamlı öneri üretebileceği bir kullanıcı seçebiliriz.
# ------------------------------------------------------------------

user_activity = (
    cf_data.groupby("author_id")["product_id"]
    .count()
    .sort_values(ascending=False)
)

print(user_activity.head(10))

author_id
1696370280     292
1288462295     204
7375781965     154
1930716686     153
2330399812     151
5060164185     150
1492711942     135
1738022745     135
10690040573    131
12640060683    118
Name: product_id, dtype: int64

In [67]:
test_user_id = 1696370280

recommend_cf_products(test_user_id, top_n=10)

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,cf_score
967,P392246,T.L.C. Framboos Glycolic Resurfacing Night Serum,Drunk Elephant,Skincare,Treatments,Face Serums,90.0,4.3492,3439.0,290028,5.945130
9,P94421,Vinoperfect Radiance Dark Spot Serum Vitamin C...,Caudalie,Skincare,Treatments,Face Serums,82.0,4.2442,2911.0,166423,2.922855
870,P415777,T.L.C. Sukari Babyfacial AHA + BHA Mask,Drunk Elephant,Skincare,Masks,Face Masks,80.0,4.2909,2554.0,274915,2.856699
1070,P427419,Hyaluronic Acid 2% + B5 Hydrating Serum,The Ordinary,Skincare,Treatments,Face Serums,15.7,4.2133,3788.0,720504,2.803213
1227,P442563,AHA 30% + BHA 2% Exfoliating Peeling Solution,The Ordinary,Skincare,Treatments,Facial Peels,9.5,4.5734,3242.0,533877,2.131271
145,P378852,GinZing Ultra-Hydrating Energy-Boosting Cream,Origins,Skincare,Moisturizers,Moisturizers,36.0,4.4010,3135.0,87846,2.043113
866,P480612,Santorini Grape Poreless Skin Cream,KORRES,Skincare,Moisturizers,Moisturizers,38.5,4.4026,3167.0,5890,2.020494
43,P456398,Ultimate Sun Protector Lotion SPF 50+ Sunscreen,Shiseido,Skincare,Sunscreen,Face Sunscreen,50.0,4.4864,2936.0,42257,1.877267
1239,P471237,Rose & Hyaluronic Acid Deep Hydration Moisturizer,fresh,Skincare,Moisturizers,Moisturizers,46.0,4.5877,1807.0,52868,1.812021
1127,P442840,Barrier+ Triple Lipid-Peptide Face Cream,Skinfix,Skincare,Moisturizers,Moisturizers,54.0,4.2924,2449.0,206494,1.790431

In [75]:
# ------------------------------------------------------------------
# UNION-BASED HYBRID RECOMMENDATION FUNCTION
#
# Bu fonksiyon content-based ve collaborative filtering önerilerini
# tek bir ortak listede birleştirir.
#
# Önceki hybrid yaklaşımında sadece content önerileri ana listeydi.
# Eğer CF önerileri ile content önerileri kesişmezse cf_score katkısı sıfır kalıyordu.
#
# Bu yeni yaklaşımda:
# - content önerileri alınır
# - CF önerileri alınır
# - iki liste union (birleşim) mantığıyla birleştirilir
# - eksik score alanları 0 ile doldurulur
# - iki skor normalize edilir
# - final hybrid score hesaplanır
# ------------------------------------------------------------------

def hybrid_recommendation(product_name, author_id, top_n=10, alpha=0.6):

    # --------------------------------------------------------------
    # 1) Content-based önerileri al
    # --------------------------------------------------------------
    content_rec = recommend_similar_products(product_name, top_n=50)

    # --------------------------------------------------------------
    # 2) Collaborative filtering önerileri al
    # --------------------------------------------------------------
    cf_rec = recommend_cf_products(author_id, top_n=50)

    if content_rec is None or cf_rec is None:
        print("Hybrid recommendation üretilemedi.")
        return None

    # --------------------------------------------------------------
    # 3) Content tarafında olmayan ama CF tarafında olan ürünleri de
    # korumak için outer merge kullanıyoruz
    # --------------------------------------------------------------
    hybrid_df = content_rec.merge(
        cf_rec[["product_id", "cf_score"]],
        on="product_id",
        how="outer"
    )

    # --------------------------------------------------------------
    # 4) Content tablosundan gelmeyen ürünlerde ürün bilgileri eksik olur
    # Bunları products_clean tablosundan tamamlıyoruz
    # --------------------------------------------------------------
    hybrid_df = hybrid_df.merge(
        products_clean[
            [
                "product_id",
                "product_name",
                "brand_name",
                "primary_category",
                "secondary_category",
                "tertiary_category",
                "price_usd",
                "rating",
                "reviews",
                "loves_count"
            ]
        ],
        on="product_id",
        how="left",
        suffixes=("", "_from_products")
    )

    # --------------------------------------------------------------
    # 5) Eğer bazı ürün bilgileri content_rec'den gelmediyse
    # products_clean'den gelen değerlerle dolduruyoruz
    # --------------------------------------------------------------
    for col in [
        "product_name",
        "brand_name",
        "primary_category",
        "secondary_category",
        "tertiary_category",
        "price_usd",
        "rating",
        "reviews",
        "loves_count"
    ]:
        fallback_col = f"{col}_from_products"
        if fallback_col in hybrid_df.columns:
            hybrid_df[col] = hybrid_df[col].fillna(hybrid_df[fallback_col])

    # Geçici kolonları temizle
    hybrid_df = hybrid_df.drop(
        columns=[col for col in hybrid_df.columns if col.endswith("_from_products")]
    )

    # --------------------------------------------------------------
    # 6) Eksik skorları 0 ile doldur
    # - content tarafından gelmeyen üründe similarity_score = 0
    # - CF tarafından gelmeyen üründe cf_score = 0
    # --------------------------------------------------------------
    hybrid_df["similarity_score"] = hybrid_df["similarity_score"].fillna(0)
    hybrid_df["cf_score"] = hybrid_df["cf_score"].fillna(0)

    # --------------------------------------------------------------
    # 7) Skorları normalize et
    #
    # similarity_score ve cf_score aynı ölçekte değildir.
    # Bu nedenle min-max normalization uyguluyoruz.
    # Eğer tüm değerler aynıysa, skorları 0 olarak bırakıyoruz.
    # --------------------------------------------------------------
    def min_max_normalize(series):
        min_val = series.min()
        max_val = series.max()

        if max_val == min_val:
            return pd.Series([0] * len(series), index=series.index)

        return (series - min_val) / (max_val - min_val)

    hybrid_df["content_score_norm"] = min_max_normalize(hybrid_df["similarity_score"])
    hybrid_df["cf_score_norm"] = min_max_normalize(hybrid_df["cf_score"])

    # --------------------------------------------------------------
    # 8) Final hybrid score hesapla
    #
    # alpha = content ağırlığı
    # (1 - alpha) = collaborative filtering ağırlığı
    # --------------------------------------------------------------
    hybrid_df["final_score"] = (
        alpha * hybrid_df["content_score_norm"] +
        (1 - alpha) * hybrid_df["cf_score_norm"]
    )

    # --------------------------------------------------------------
    # 9) Sonuçları sırala
    # --------------------------------------------------------------
    hybrid_df = hybrid_df.sort_values("final_score", ascending=False)

    # --------------------------------------------------------------
    # 10) Sonuç tablosunda gösterilecek sütunlar
    # --------------------------------------------------------------
    result_cols = [
        "product_id",
        "product_name",
        "brand_name",
        "primary_category",
        "secondary_category",
        "tertiary_category",
        "price_usd",
        "rating",
        "reviews",
        "loves_count",
        "similarity_score",
        "cf_score",
        "content_score_norm",
        "cf_score_norm",
        "final_score"
    ]

    result_cols = [col for col in result_cols if col in hybrid_df.columns]

    return hybrid_df[result_cols].head(top_n)

In [76]:
# ------------------------------------------------------------------
# UNION-BASED HYBRID RECOMMENDATION TEST
#
# Bu örnekte:
# - ürün bazlı content recommendation
# - kullanıcı bazlı CF recommendation
# birlikte kullanılacaktır.
# ------------------------------------------------------------------

hybrid_recommendation(
    product_name="Radiant Creamy Concealer",
    author_id=1696370280,
    top_n=10
)

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,similarity_score,cf_score,content_score_norm,cf_score_norm,final_score
33,P422077,Mini Radiant Creamy Concealer,NARS,Mini Size,Makeup,NaN,15.0,4.1253,1708.0,444366.0,0.874305,0.00000,1.000000,0.0,0.600000
96,P505043,Mini Radiant Creamy Concealer and Afterglow Li...,NARS,Makeup,Value & Gift Sets,NaN,25.0,NaN,NaN,2535.0,0.690995,0.00000,0.790336,0.0,0.474202
56,P449107,Synchro Skin Self-Refreshing Concealer,Shiseido,Makeup,Face,Concealer,31.0,4.4394,1311.0,38828.0,0.594693,0.00000,0.680190,0.0,0.408114
12,P392246,T.L.C. Framboos Glycolic Resurfacing Night Serum,Drunk Elephant,Skincare,Treatments,Face Serums,90.0,4.3492,3439.0,290028.0,0.000000,5.94513,0.000000,1.0,0.400000
74,P473173,Radiant Creamy Liquid Color Corrector,NARS,Makeup,Face,Color Correct,30.0,3.5045,111.0,28551.0,0.553201,0.00000,0.632733,0.0,0.379640
66,P462720,Soft Matte Complete Foundation,NARS,Makeup,Face,Foundation,42.0,4.1135,1851.0,152923.0,0.538023,0.00000,0.615372,0.0,0.369223
23,P416200,Soft Matte Complete Concealer,NARS,Makeup,Face,Concealer,32.0,4.4704,2668.0,412271.0,0.537174,0.00000,0.614401,0.0,0.368640
48,P440044,Studio Skin Flawless Oil-Free 24 Hour Concealer,Smashbox,Makeup,Face,Concealer,29.0,4.3951,739.0,25465.0,0.526362,0.00000,0.602034,0.0,0.361221
2,P122914,"Airbrush Concealer Illuminates, Perfects",CLINIQUE,Makeup,Face,Concealer,28.0,4.1732,462.0,20466.0,0.516906,0.00000,0.591220,0.0,0.354732
88,P482262,Backstage Concealer,Dior,Makeup,Face,Concealer,29.0,4.4750,1341.0,146408.0,0.506883,0.00000,0.579755,0.0,0.347853

In [69]:
hybrid_recommendation(
    product_name="Radiant Creamy Concealer",
    author_id=1696370280,
    top_n=10
)

,product_id,product_name,brand_name,primary_category,secondary_category,tertiary_category,price_usd,rating,reviews,loves_count,similarity_score,cf_score,final_score
0,P422077,Mini Radiant Creamy Concealer,NARS,Mini Size,Makeup,NaN,15.0,4.1253,1708.0,444366,0.874305,0.0,0.524583
1,P505043,Mini Radiant Creamy Concealer and Afterglow Li...,NARS,Makeup,Value & Gift Sets,NaN,25.0,NaN,NaN,2535,0.690995,0.0,0.414597
2,P449107,Synchro Skin Self-Refreshing Concealer,Shiseido,Makeup,Face,Concealer,31.0,4.4394,1311.0,38828,0.594693,0.0,0.356816
3,P473173,Radiant Creamy Liquid Color Corrector,NARS,Makeup,Face,Color Correct,30.0,3.5045,111.0,28551,0.553201,0.0,0.331921
4,P462720,Soft Matte Complete Foundation,NARS,Makeup,Face,Foundation,42.0,4.1135,1851.0,152923,0.538023,0.0,0.322814
5,P416200,Soft Matte Complete Concealer,NARS,Makeup,Face,Concealer,32.0,4.4704,2668.0,412271,0.537174,0.0,0.322304
6,P440044,Studio Skin Flawless Oil-Free 24 Hour Concealer,Smashbox,Makeup,Face,Concealer,29.0,4.3951,739.0,25465,0.526362,0.0,0.315817
7,P122914,"Airbrush Concealer Illuminates, Perfects",CLINIQUE,Makeup,Face,Concealer,28.0,4.1732,462.0,20466,0.516906,0.0,0.310144
8,P482262,Backstage Concealer,Dior,Makeup,Face,Concealer,29.0,4.4750,1341.0,146408,0.506883,0.0,0.304130
9,P470512,Original Liquid Mineral Concealer,bareMinerals,Makeup,Face,Concealer,28.0,4.3244,706.0,15997,0.497470,0.0,0.298482

In [70]:
# ------------------------------------------------------------------
# CONTENT VE CF ÖNERİLERİ ARASINDAKİ ORTAK ÜRÜNLERİ KONTROL ETME
#
# Amaç:
# Hybrid recommendation çıktısında cf_score değerlerinin neden 0 olduğunu
# anlamak için content-based ve collaborative filtering önerileri arasında
# ortak ürün olup olmadığını kontrol ediyoruz.
#
# Eğer ortak ürün sayısı çok düşükse veya sıfırsa,
# mevcut hybrid mantığı content odaklı kalır.
# ------------------------------------------------------------------

content_rec = recommend_similar_products(
    product_name="Radiant Creamy Concealer",
    top_n=50
)

cf_rec = recommend_cf_products(
    author_id=1696370280,
    top_n=50
)

# İki öneri listesi arasındaki ortak product_id'leri bul
common_products = set(content_rec["product_id"]).intersection(set(cf_rec["product_id"]))

print("Content öneri sayısı:", content_rec.shape[0])
print("CF öneri sayısı:", cf_rec.shape[0])
print("Ortak ürün sayısı:", len(common_products))
print("Ortak ürünler:", common_products)

Content öneri sayısı: 50
CF öneri sayısı: 50
Ortak ürün sayısı: 0
Ortak ürünler: set()

In [71]:
# ------------------------------------------------------------------
# AKTİF OTURUMDA FONKSİYONLAR TANIMLI MI KONTROLÜ
#
# Amaç:
# Notebook'ta daha önce yazdığımız recommendation fonksiyonlarının
# mevcut kernel oturumunda tanımlı olup olmadığını kontrol etmek.
# ------------------------------------------------------------------

print("recommend_similar_products tanımlı mı?:", "recommend_similar_products" in globals())
print("recommend_cf_products tanımlı mı?:", "recommend_cf_products" in globals())
print("hybrid_recommendation tanımlı mı?:", "hybrid_recommendation" in globals())

recommend_similar_products tanımlı mı?: True
recommend_cf_products tanımlı mı?: True
hybrid_recommendation tanımlı mı?: True

In [72]:
# ------------------------------------------------------------------
# CONTENT VE CF ÖNERİLERİ ARASINDAKİ ORTAK ÜRÜNLERİ KONTROL ETME
#
# Amaç:
# Hybrid recommendation çıktısında cf_score değerlerinin neden 0 olduğunu
# anlamak için content-based ve collaborative filtering önerileri arasında
# ortak ürün olup olmadığını kontrol ediyoruz.
#
# Eğer ortak ürün sayısı çok düşükse veya sıfırsa,
# mevcut hybrid mantığı content odaklı kalır.
# ------------------------------------------------------------------

content_rec = recommend_similar_products(
    product_name="Radiant Creamy Concealer",
    top_n=50
)

cf_rec = recommend_cf_products(
    author_id=1696370280,
    top_n=50
)

# İki öneri listesi arasındaki ortak product_id'leri bul
common_products = set(content_rec["product_id"]).intersection(set(cf_rec["product_id"]))

print("Content öneri sayısı:", content_rec.shape[0])
print("CF öneri sayısı:", cf_rec.shape[0])
print("Ortak ürün sayısı:", len(common_products))
print("Ortak ürünler:", common_products)

Content öneri sayısı: 50
CF öneri sayısı: 50
Ortak ürün sayısı: 0
Ortak ürünler: set()